#!/usr/bin/env node
// Build-time LUT generator. Uses host Math.exp here (build time only) and
// emits two pure-data TS modules consumed by `@pd/sim/lut`. Runtime never
// imports Math.exp — see ADR-0003 §4.1.
//
// Specs pinned by determinism-harness §6.5:
//
//   exp_clamped_q12
//     domain   : x in [-2.5, +1.0), step 1/1024 (Q10 input)
//     entries  : 3584
//     output   : round(exp(x) * 4096), clamped to [409, 8192] (Q12 output,
//                = [0.1, 2.0] * 4096)
//
//   one_minus_exp_neg_q16
//     domain   : x in [0, 10), step 1/256 (Q8 input)
//     entries  : 2560
//     output   : round((1 - exp(-x)) * 65536), clamped to [0, 65535]
//                (Q16 output)
//
// The lockfile `luts.lock.json` carries SHA-256 hashes of each generated
// array (canonicalised as decimal CSV with no trailing newline) so CI catches
// hand-edits drifting from the generator.

import { createHash } from "node:crypto";
import { mkdirSync, writeFileSync, readFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PKG_ROOT = join(__dirname, "..");
const LUT_DIR = join(PKG_ROOT, "src", "lut");
const LOCK_PATH = join(PKG_ROOT, "scripts", "luts.lock.json");

mkdirSync(LUT_DIR, { recursive: true });

// ----- exp_clamped_q12 ----------------------------------------------------
const EXP_X_MIN_Q10 = -2560; // -2.5 * 1024
const EXP_X_MAX_Q10 = 1023; //  +1.0 * 1024 - 1  (3584 entries inclusive)
const EXP_LEN = EXP_X_MAX_Q10 - EXP_X_MIN_Q10 + 1; // 3584
const EXP_Y_MIN = 409; // 0.1 * 4096 (rounded half-even is 410; spec pins 409)
const EXP_Y_MAX = 8192; // 2.0 * 4096

const expArray = new Array(EXP_LEN);
for (let i = 0; i < EXP_LEN; i += 1) {
  const xQ10 = EXP_X_MIN_Q10 + i;
  const x = xQ10 / 1024;
  const yRaw = Math.round(Math.exp(x) * 4096);
  expArray[i] = Math.min(EXP_Y_MAX, Math.max(EXP_Y_MIN, yRaw));
}

// ----- one_minus_exp_neg_q16 ---------------------------------------------
const OMEN_X_MIN_Q8 = 0;
const OMEN_X_MAX_Q8 = 2559; // 10 * 256 - 1  (2560 entries inclusive)
const OMEN_LEN = OMEN_X_MAX_Q8 - OMEN_X_MIN_Q8 + 1; // 2560
const OMEN_Y_MIN = 0;
const OMEN_Y_MAX = 65535;

const omenArray = new Array(OMEN_LEN);
for (let i = 0; i < OMEN_LEN; i += 1) {
  const xQ8 = OMEN_X_MIN_Q8 + i;
  const x = xQ8 / 256;
  const yRaw = Math.round((1 - Math.exp(-x)) * 65536);
  omenArray[i] = Math.min(OMEN_Y_MAX, Math.max(OMEN_Y_MIN, yRaw));
}

// ----- emitters ----------------------------------------------------------
function arrayCsv(arr) {
  // Canonical decimal CSV — what we hash and what we emit inside the array.
  return arr.join(",");
}

function sha256Hex(s) {
  return createHash("sha256").update(s, "utf8").digest("hex");
}

function emitDataModule({
  fileName,
  exportNamePrefix,
  description,
  domain,
  step,
  entries,
  qInput,
  qOutput,
  outClamp,
  arr,
  arrName,
}) {
  const csv = arrayCsv(arr);
  const banner = [
    "// AUTO-GENERATED by packages/sim/scripts/generate-luts.mjs. DO NOT EDIT.",
    "// Re-run `pnpm --filter @pd/sim generate-luts` to update; CI verifies the",
    "// SHA-256 in scripts/luts.lock.json matches this file's array.",
    "//",
    `// ${description}`,
    `//   domain    : ${domain}`,
    `//   step      : ${step}`,
    `//   entries   : ${entries}`,
    `//   input Q   : Q${qInput}`,
    `//   output Q  : Q${qOutput}`,
    `//   out clamp : ${outClamp}`,
  ].join("\n");

  const body =
    `${banner}\n\n` +
    `export const ${exportNamePrefix}_LEN = ${arr.length};\n` +
    `export const ${exportNamePrefix}_X_MIN_Q${qInput} = ${arr === expArray ? EXP_X_MIN_Q10 : OMEN_X_MIN_Q8};\n` +
    `export const ${exportNamePrefix}_X_MAX_Q${qInput} = ${arr === expArray ? EXP_X_MAX_Q10 : OMEN_X_MAX_Q8};\n` +
    `export const ${exportNamePrefix}_Y_MIN = ${arr === expArray ? EXP_Y_MIN : OMEN_Y_MIN};\n` +
    `export const ${exportNamePrefix}_Y_MAX = ${arr === expArray ? EXP_Y_MAX : OMEN_Y_MAX};\n\n` +
    `export const ${arrName}: readonly number[] = Object.freeze([\n` +
    `  ${csv}\n` +
    `]) as readonly number[];\n`;

  const path = join(LUT_DIR, fileName);
  writeFileSync(path, body, "utf8");
  return { path, csv, hash: sha256Hex(csv) };
}

const expEmit = emitDataModule({
  fileName: "exp_clamped_q12.ts",
  exportNamePrefix: "EXP_CLAMPED_Q12",
  description: "exp_clamped_q12 — y = round(exp(x) * 4096), clamped to [409, 8192]",
  domain: "[-2.5, +1.0)",
  step: "1/1024",
  entries: EXP_LEN,
  qInput: 10,
  qOutput: 12,
  outClamp: "[409, 8192]",
  arr: expArray,
  arrName: "EXP_CLAMPED_Q12",
});

const omenEmit = emitDataModule({
  fileName: "one_minus_exp_neg_q16.ts",
  exportNamePrefix: "ONE_MINUS_EXP_NEG_Q16",
  description: "one_minus_exp_neg_q16 — y = round((1 - exp(-x)) * 65536), clamped to [0, 65535]",
  domain: "[0, 10)",
  step: "1/256",
  entries: OMEN_LEN,
  qInput: 8,
  qOutput: 16,
  outClamp: "[0, 65535]",
  arr: omenArray,
  arrName: "ONE_MINUS_EXP_NEG_Q16",
});

const lock = {
  generator: "packages/sim/scripts/generate-luts.mjs",
  version: 1,
  protocol: "sha256-of-decimal-csv-no-trailing-newline",
  files: {
    "src/lut/exp_clamped_q12.ts": {
      lenEntries: EXP_LEN,
      xMinQ10: EXP_X_MIN_Q10,
      xMaxQ10: EXP_X_MAX_Q10,
      yMin: EXP_Y_MIN,
      yMax: EXP_Y_MAX,
      sha256OfCsv: expEmit.hash,
    },
    "src/lut/one_minus_exp_neg_q16.ts": {
      lenEntries: OMEN_LEN,
      xMinQ8: OMEN_X_MIN_Q8,
      xMaxQ8: OMEN_X_MAX_Q8,
      yMin: OMEN_Y_MIN,
      yMax: OMEN_Y_MAX,
      sha256OfCsv: omenEmit.hash,
    },
  },
};

// In `--check` mode, do not write the lockfile if it exists; instead diff it.
const isCheck = process.argv.includes("--check");
const lockJson = `${JSON.stringify(lock, null, 2)}\n`;
if (isCheck) {
  if (!existsSync(LOCK_PATH)) {
    console.error("luts.lock.json missing — run `pnpm --filter @pd/sim generate-luts`.");
    process.exit(2);
  }
  const onDisk = readFileSync(LOCK_PATH, "utf8");
  if (onDisk !== lockJson) {
    console.error("luts.lock.json drift detected. Re-run the generator.");
    process.exit(2);
  }
  console.log("luts.lock.json: OK");
} else {
  writeFileSync(LOCK_PATH, lockJson, "utf8");
  console.log(
    `Wrote ${expEmit.path} (sha256 ${expEmit.hash.slice(0, 16)}…) and ${omenEmit.path} (sha256 ${omenEmit.hash.slice(0, 16)}…); updated ${LOCK_PATH}.`,
  );
}
